FROM jenkins/jenkins:lts
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
COPY jenkins.yaml /usr/share/jenkins/ref/jenkins.yaml
COPY jobs.yaml /usr/share/jenkins/ref/jobs.yaml
ENV JENKINS_HOME /var/jenkins_home
ARG JAVA_OPTS
ENV JAVA_OPTS "-Djenkins.install.runSetupWizard=false ${JAVA_OPTS:-}"
ENV CASC_JENKINS_CONFIG "/usr/share/jenkins/ref/"

EXPOSE 8080
EXPOSE 50000




RUN xargs /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt