apiVersion: apps/v1
kind: Deployment
metadata:
  name: targapp-one
  labels:
    app: targapp-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: targapp-one
  template:
    metadata:
      labels:
        app: targapp-one
    spec:
      containers:
      - name: targapp-one
        image: alxl/pipeline-demo:latest
        ports:
        - containerPort: 8080
      
