apiVersion: v1
kind: Service
metadata:
  name: targapp-two-service
spec:
  type: NodePort
  selector:
    app: targapp-two
  ports:
  - name: web-interface
    protocol: TCP
    nodePort: 30801
    port: 8080
    targetPort: 8080