apiVersion: v1
kind: Service
metadata:
  name: targapp-one-service
spec:
  type: NodePort
  selector:
    app: targapp-one
  ports:
  - name: web-interface
    protocol: TCP
    nodePort: 30800
    port: 8080
    targetPort: 8080